update msa and dynamic toll functions
camsys/tm2py pull request #37
Opened 2023-01-12 15:04 UTC by ychtw

2023-01-12 23:04 UTC, i-am-sijia requested changes
LGTM. And you have tested and checked the outputs, correct?

2023-01-12 23:04 UTC, i-am-sijia commented on tm2py/components/network/highway/highway_assign.py
> +        run_dynamic_toll = self.controller.config.highway.tolls.run_dynamic_toll
```suggestion
        run_dynamic_toll = self.config.tolls.run_dynamic_toll
```

2023-01-12 23:04 UTC, i-am-sijia commented on tm2py/components/network/highway/highway_assign.py
> +        apply_msa = self.controller.config.highway.msa.apply_msa
```suggestion
        apply_msa = self.config.msa.apply_msa
```

2023-01-12 23:04 UTC, i-am-sijia commented on tm2py/components/network/highway/highway_assign.py
> +                            assign_spec["stopping_criteria"]["max_iterations"] = self.controller.config.highway.tolls.dynamic_toll_inner_iter
```suggestion
                            assign_spec["stopping_criteria"]["max_iterations"] = self.config.tolls.dynamic_toll_inner_iter
```

2023-01-12 23:04 UTC, i-am-sijia commented on tm2py/components/network/highway/highway_assign.py
> +                                assign_spec["stopping_criteria"]["max_iterations"] -= self.controller.config.highway.tolls.dynamic_toll_inner_iter
```suggestion
                                assign_spec["stopping_criteria"]["max_iterations"] -= self.config.tolls.dynamic_toll_inner_iter
```
Can we really reduce the iteration here? Meaning does the assignment keep and restart from the previous state (with the inner iterations)?

2023-01-12 23:04 UTC, i-am-sijia commented on tm2py/components/network/highway/highway_assign.py
> +                            if dynamic_toll_iteration < 5:
This block of code about dynamic tolling makes the main function `run()` really long, suggest splitting it out into a `_run_dynamic_tolling_assignment()` function. This is not urgent to address, just esthetic.

2023-01-13 17:59 UTC, ychtw commented on tm2py/components/network/highway/highway_assign.py
> +        apply_msa = self.controller.config.highway.msa.apply_msa
updated in 5eacf05

2023-01-13 18:00 UTC, ychtw commented on tm2py/components/network/highway/highway_assign.py
> +                            assign_spec["stopping_criteria"]["max_iterations"] = self.controller.config.highway.tolls.dynamic_toll_inner_iter
updated in 5eacf05

2023-01-13 18:00 UTC, ychtw commented on tm2py/components/network/highway/highway_assign.py
> +        run_dynamic_toll = self.controller.config.highway.tolls.run_dynamic_toll
updated in 5eacf05

2023-01-13 19:41 UTC, ychtw commented on tm2py/components/network/highway/highway_assign.py
> +                                assign_spec["stopping_criteria"]["max_iterations"] -= self.controller.config.highway.tolls.dynamic_toll_inner_iter
updated in d65a72d

2023-01-13 21:50 UTC, i-am-sijia approved these changes

2023-01-13 21:52 UTC, i-am-sijia commented
Just approved the dynamic tolling changes. TO DO: @ychtw the MSA logic still needs to be refactored to reflect what we discussed today. Please create another PR for that.

2023-01-13 21:56 UTC, merged